asset_path: /workspace/isaaclab/source/isaaclab_tasks/isaaclab_tasks/manager_based/rock_grasp/scene_objects/rock_1/Rock-6-solid.stl
usd_dir: /workspace/isaaclab/source/isaaclab_tasks/isaaclab_tasks/manager_based/rock_grasp/scene_objects/rock_1
usd_file_name: rock.usd
force_usd_conversion: true
make_instanceable: true
mass_props:
  mass: null
  density: 2582
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
collision_approximation: convexDecomposition
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2025-04-07 at 12:52:55.
##
